### ISSUE TITLE
[BUG] rename the three "Hexadecimal" files, for Windows

### ISSUE THREAD

**Issue by sboosali** [qfpl/digit#15]
Since file paths are case-insensitive on Windows, you lose some of the files in the repo/sdist.

```

> git clone https://github.com/qfpl/digit

> dir digit\src\Data\Digit\H*.hs

 Directory of C:\Users\Spiros\haskell\digit\src\Data\Digit

 07/10/2018  05:27 PM             7,878 Hexadecimal.hs
               1 File(s)          7,878 bytes


```

I'd do it myself on a non-Windows machine, but I assume you all would want to pick the naming convention :-)

**Comment by mankyKitty** [comment]
This should now be fixed as part of #18 :+1:
